// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATKw8QXWUNBcuRbIVM6k6BUo4xtuE8cnU',
    appId: '1:238045160779:web:db475b0d42572995cb74ce',
    messagingSenderId: '238045160779',
    projectId: 'piccrud',
    authDomain: 'piccrud.firebaseapp.com',
    storageBucket: 'piccrud.appspot.com',
    measurementId: 'G-VJ97GZ5LZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARJrLuZGjexDnVJGgjfBve4rfXatVapD4',
    appId: '1:238045160779:android:bb4f0ecaa5d36707cb74ce',
    messagingSenderId: '238045160779',
    projectId: 'piccrud',
    storageBucket: 'piccrud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ife4xAuvoS6LGlLmc4BSJXl3ubUug48',
    appId: '1:238045160779:ios:9ea04db62e343e4dcb74ce',
    messagingSenderId: '238045160779',
    projectId: 'piccrud',
    storageBucket: 'piccrud.appspot.com',
    iosBundleId: 'com.example.picFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ife4xAuvoS6LGlLmc4BSJXl3ubUug48',
    appId: '1:238045160779:ios:9ea04db62e343e4dcb74ce',
    messagingSenderId: '238045160779',
    projectId: 'piccrud',
    storageBucket: 'piccrud.appspot.com',
    iosBundleId: 'com.example.picFirebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATKw8QXWUNBcuRbIVM6k6BUo4xtuE8cnU',
    appId: '1:238045160779:web:605e99ceae4987b0cb74ce',
    messagingSenderId: '238045160779',
    projectId: 'piccrud',
    authDomain: 'piccrud.firebaseapp.com',
    storageBucket: 'piccrud.appspot.com',
    measurementId: 'G-67LYJFJ1ZS',
  );
}
